name: Docker Image CI

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env: 
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Build and tag the Docker image
      run: |
        docker --version
        docker build -t udagram-api-feed ./udagram-api-feed
        docker tag udagram-api-feed nhathuu2107/udagram-api-feed:v1

        docker build -t udagram-api-user ./udagram-api-user
        docker tag udagram-api-user nhathuu2107/udagram-api-user:v1

        docker build -t udagram-frontend ./udagram-frontend
        docker tag udagram-frontend nhathuu2107/udagram-frontend:v1

        docker build -t udagram-reverseproxy ./udagram-reverseproxy
        docker tag udagram-reverseproxy nhathuu2107/udagram-reverseproxy:v1

    - name: Push the Docker image
      run: |
        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        docker push nhathuu2107/udagram-api-feed:v1
        docker push nhathuu2107/udagram-api-user:v1
        docker push nhathuu2107/udagram-frontend:v1
        docker push nhathuu2107/udagram-reverseproxy:v1